name: Educational Neuroscience
favicon: null
layout_spectrum: 0.2512529550585896
typography_spectrum: 0.13638501963578165
title: A blog based on the scientific journal Educational Neuroscience
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d3ccb0'
    - '#b1a996'
    - '#8c652c'
    - '#f0f17c'
  brandStrength: 0.5
  lightness: 0.6433965519536287
  saturation: 0.6628439773339778
  rhythmicContrast: 0.2875393044669181
purpose: []
